version: '3'
services:
  bot:
    build: .
    volumes:
      - ./src:/app/src
    environment:
      TOKEN: "5350695667:AAFg1bZDiylrvAbcUUKZAm00Eia-zcnkgOo"
      GMAIL_PASSWORD: ""
      ADMIN_ID: "[183119677]"
      PATH_DB: "/app/resources/dataBaseStudents.db"
    command: python src/bot.py